import Head from "next/head";
import Factions from "../components/Factions";

export default function Home() {
  return (
    <>
      <Head>
        <title>Warship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Factions />
      </main>
    </>
  );
}
